# Generated by Django 5.2.10 on 2026-02-08 17:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etiqueta',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-fecha_resena']},
        ),
        migrations.AlterField(
            model_name='etiqueta',
            name='nombre',
            field=models.CharField(help_text='Nombre de la etiqueta (único)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='categoria',
            field=models.ForeignKey(blank=True, help_text='Categoría a la que pertenece la película', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas', to='streaming.categoria'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.PositiveIntegerField(help_text='Duración de la película en minutos'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, help_text='Etiquetas asociadas a la película', related_name='peliculas', to='streaming.etiqueta'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de la película', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='usuarios',
            field=models.ManyToManyField(blank=True, help_text='Usuarios que han reseñado la película', related_name='peliculas_resenadas', through='streaming.Resena', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='resena',
            name='pelicula',
            field=models.ForeignKey(help_text='Película reseñada', on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to='streaming.pelicula'),
        ),
        migrations.AlterField(
            model_name='resena',
            name='puntuacion',
            field=models.IntegerField(help_text='Puntuación de la reseña (0-10)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='resena',
            name='usuario',
            field=models.ForeignKey(help_text='Usuario que reseña la película', on_delete=django.db.models.deletion.CASCADE, related_name='resenas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='FichaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma_original', models.CharField(blank=True, max_length=30)),
                ('pais', models.CharField(blank=True, max_length=60)),
                ('trailer_url', models.URLField(blank=True)),
                ('pelicula', models.OneToOneField(help_text='Ficha técnica asociada (1:1)', on_delete=django.db.models.deletion.CASCADE, related_name='ficha_tecnica', to='streaming.pelicula')),
            ],
        ),
    ]
