# Generated by Django 5.2.10 on 2026-01-12 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoría (único)', max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la categoría (opcional)')),
            ],
            options={
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la etiqueta', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la película', max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción de la película')),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, help_text='Precio de la película', max_digits=6)),
                ('fecha_estreno', models.DateField(help_text='Fecha de estreno de la película')),
                ('duracion', models.IntegerField(help_text='Duración de la película en minutos')),
                ('activa', models.BooleanField(default=True, help_text='Indica si la película está activa')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación de la película')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Fecha de última actualización de la película')),
                ('categoria', models.ForeignKey(help_text='Categoría a la que pertenece la película', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peliculas', to='streaming.categoria')),
                ('etiquetas', models.ManyToManyField(blank=True, help_text='Etiquetas asociadas a la película', to='streaming.etiqueta')),
            ],
            options={
                'verbose_name': 'Película',
                'verbose_name_plural': 'Películas',
                'ordering': ['-fecha_estreno'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.CharField(blank=True, help_text='URL de la imagen de perfil (opcional)', max_length=255)),
                ('fecha_nacimiento', models.DateField(blank=True, help_text='Fecha de nacimiento (opcional)', null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.IntegerField(help_text='Puntuación de la reseña (0-10)')),
                ('comentario', models.TextField(blank=True, help_text='Comentario de la reseña (opcional)')),
                ('fecha_resena', models.DateTimeField(auto_now_add=True, help_text='Fecha de la reseña')),
                ('pelicula', models.ForeignKey(help_text='Película reseñada', on_delete=django.db.models.deletion.CASCADE, to='streaming.pelicula')),
                ('usuario', models.ForeignKey(help_text='Usuario que reseña la película', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pelicula',
            name='usuarios',
            field=models.ManyToManyField(help_text='Usuarios que han reseñado la película', through='streaming.Resena', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='resena',
            constraint=models.UniqueConstraint(fields=('pelicula', 'usuario'), name='unique_resena'),
        ),
    ]
